name: Build macOS App

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*"
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Compile Kagoj
        run: bash build.sh

      - name: Zip the Application
        run: zip -r Kagoj_v1.1.1.zip Kagoj.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kagoj-macOS-Compiled
          path: Kagoj_v1.1.1.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Kagoj_v1.1.1.zip
          generate_release_notes: true
